services:
  booky-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booky-backend-freetier
    environment:
      # Database Configuration (RDS)
      DATABASE_URL: ${DATABASE_URL:-jdbc:postgresql://localhost:5432/booky}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-admin}
      DATABASE_NAME: ${DATABASE_NAME:-booky}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-production}
      
      # JVM Options for t2.micro
      JAVA_OPTS: "-Xms256m -Xmx512m -XX:MaxMetaspaceSize=128m -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication"
      
      # Logging
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      
      # Security
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-minimum-32-characters}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
      
      # CORS
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-*}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS:-GET,POST,PUT,DELETE,OPTIONS}
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS:-*}
    ports:
      - "8080:8080"
    networks:
      - booky-freetier-network
    restart: unless-stopped
    # Optimización de recursos para t2.micro
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Logging optimizado
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # PostgreSQL local solo para desarrollo (comentado para Free Tier)
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: booky-postgres-local
  #   environment:
  #     POSTGRES_DB: booky
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: admin
  #     PGDATA: /var/lib/postgresql/data/pgdata
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./scripts/database_schema_updated.sql:/docker-entrypoint-initdb.d/00-schema.sql
  #   networks:
  #     - booky-freetier-network
  #   restart: unless-stopped
  #   # Optimización para desarrollo local
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 256M
  #         cpus: '0.3'
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres -d booky"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

# Adminer solo para desarrollo local (comentado para Free Tier)
# adminer:
#   image: adminer:4.8.1
#   container_name: booky-adminer-local
#   ports:
#     - "8081:8080"
#   networks:
#     - booky-freetier-network
#   restart: unless-stopped
#   depends_on:
#     - postgres

# Volumes comentados para Free Tier (usa RDS)
# volumes:
#   postgres_data:
#     driver: local

networks:
  booky-freetier-network:
    driver: bridge 