app = "booky-be"
primary_region = "gru"
console_command = "/cnb/process/web"

[build]

[env]
  SPRING_PROFILES_ACTIVE = "prod"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[checks]
  [checks.health_check]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    path = "/actuator/health"
    port = 8080
    protocol = "http"
    timeout = "10s"
    tls_skip_verify = false

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/static/"
