spring:
  application:
    name: booky-be
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    name: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  jackson:
    property:
      naming-strategy: SNAKE_CASE
  profiles:
    active: ${SCOPE}
    default: local
  jmx:
    enabled: false

cloudinary:
  cloud-name: dfsfkyyx7
  api-key: 438652139556741
  api-secret: 1QsWsAAwvBelPw1kc4TWdLNSrjc